name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - name: ssh docker login   
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TENCENT_CLOUD_IP }} 
          username: ${{ secrets.TENCENT_CLOUD_NAME }} 
          password: ${{ secrets.TENCENT_CLOUD_PASSWORD }} 
          script:  cd /tmp/scraper && sh do.sh
